CREATE TABLE [dbo].[Users]
(
  Id  UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  [Name] NVARCHAR(255) NOT NULL,
  Email NVARCHAR(255) NOT NULL,
  [Password] NVARCHAR(255) NOT NULL,
  CreatedAt DATETIME2 (7) NOT NULL DEFAULT GETDATE(),
  UpdatedAt DATETIME2 (7) NOT NULL DEFAULT GETDATE()
)
